### ISSUE TITLE
IOError: [Errno 2] No such file or directory: queries.json

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#22]
IOError: [Errno 2] No such file or directory: '/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg/exporters/resources\\queries.json'

throwing above err when tried to export_to_graph and/or export_to_report from source db where all commits, users etc tables created by gitana.

I don't see such file in gitana's test directory too.

	l(mmopuru@mmopuru-service)-(0)-(08:31 AM Sun Jun 18)->
	m-(/dbc/blr-dbc301/mmopuru)-(26 files, 847Mb)--> cat report.json
	{"report":
			{"project": "papyrus",
			 "time_span": "this_year",
			 "repo_activity": {"names": ["vcf_repo"],
							   "measures": ["#commits", "#repo-users"]}
			 }
	}
	l(mmopuru@mmopuru-service)-(0)-(08:33 AM Sun Jun 18)->
	m-(/dbc/blr-dbc301/mmopuru)-(26 files, 847Mb)--> cat graph.json
	{"graph":
			{"name": "users-on-files",
			 "params": {"project": "papyrus",
									"repo": "vcf_repo",
									"nodecolor": "random",
									"edgecolor": "black",
									"type": "undirected"}
			 }
	}

**Comment by valeriocos** [comment]
thanks for reporting this issue. I've just committed a new setup.py that should fix the import of queries.json.
Wrt the directory test, it's not included in the installation.

**Comment by mopuru-murali** [comment]
Still the issue persists.

you should change 

	INPUT_PATH = os.path.dirname(resources.__file__) + "\queries.json"

to

	INPUT_PATH = os.path.join(os.path.dirname(resources.__file__), 'queries.json')

inside 

	exporters/graph/graph_exporter.py
	exporters/report/report_exporter.py

so that OS specific path will be assigned.

**Comment by valeriocos** [comment]
Thanks for the hint, I've modified the files as you suggested.
Note that Gitana is developped and tested on Windows. So if you use other OSs, you may find other path-related problems.
